name: Validate PR on develop branch

on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment-on-integration-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Check Node.js version
        run: node -v

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI and plugins
        run: |
          npm install --global @salesforce/cli
          sf --version
          echo y | sf plugins install sfdx-git-delta

      - name: Clear cache and install sf scanner plugin
        run: |
          rm -rf ~/.local/share/sfdx
          sf plugins install @salesforce/sfdx-scanner

      - name: Read PR Body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo $PR_BODY > pr_body.txt
          node parsePR.js
          TESTS=$(cat testsToRun.txt)
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV

      - name: Populate auth file with SF_URL
        run: echo ${{ secrets.SFDX_INTEGRATION_URL }} > SF_INTEGRATION_URL.txt

      - name: Authenticate to Integration Org
        run: sf auth:sfdxurl:store -f SF_INTEGRATION_URL.txt -s -a integration

      - name: Create delta packages
        run: |
          mkdir changed-sources
          sf sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

      - name: Set correct environment variables
        run: |
          echo "SF_LAZY_LOAD_MODULES=true" >> $GITHUB_ENV
          echo "SF_DISABLE_AUTOUPDATE=true" >> $GITHUB_ENV
          echo "SF_AUTOUPDATE_DISABLE=true" >> $GITHUB_ENV

      - name: Scan code
        run: |
          cd changed-sources
          sf scanner:run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'
          cd ..

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: changed-sources/apexScanResults.sarif
          
      - name: Deploy delta changes
        run: |
          if [ -z "${APEX_TESTS}" ]; then
            # Pas de tests spécifiés
            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level NoTestRun --json 2>&1)
          elif [ "${APEX_TESTS}" == "all" ]; then
            # Exécuter tous les tests locaux
            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunLocalTests --json 2>&1)
          else
            # Exécuter des tests spécifiques
            result=$(sf deploy metadata -d "changed-sources/force-app" --dry-run --test-level RunSpecifiedTests --runtests "${APEX_TESTS}" --json 2>&1)
          fi

          # Afficher le résultat brut pour débogage
          echo "Deployment result: $result"

          if ! echo "$result" | jq -e . >/dev/null 2>&1; then
            echo "::error::Invalid JSON response from deployment command."
            exit 1
          fi

          echo "Check code coverage warnings."
          coverage_warnings=$(echo "$result" | jq -r '.result.codeCoverageWarnings' 2>/dev/null)
          if [ -n "$coverage_warnings" ]; then
            echo "::error::Code Coverage Issue."
            exit 1
          fi

      - name: Cleanup temporary files
        run: rm -f pr_body.txt testsToRun.txt SF_INTEGRATION_URL.txt
