name: Validate PR on develop branch

on:
  pull_request:
    types: [opened, synchronize]
    branches: [develop]
    paths:
      - 'force-app/**'

jobs:
  validate-deployment-on-integration-org:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '^18.18.0'

      - name: Check Node.js version
        run: node -v

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI and plugins
        run: |
          npm install sfdx-cli --global
          sfdx version
          echo y | sfdx plugins:install sfdx-git-delta @salesforce/sfdx-scanner

      - name: Read PR Body
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          echo $PR_BODY > pr_body.txt
          node parsePR.js
          TESTS=$(cat testsToRun.txt)
          echo "APEX_TESTS=$TESTS" >> $GITHUB_ENV

      - name: Populate auth file with SFDX_URL
        run: echo ${{ secrets.SFDX_INTEGRATION_URL }} > SFDX_INTEGRATION_URL.txt

      - name: Authenticate to Integration Org
        run: sfdx auth:sfdxurl:store -f SFDX_INTEGRATION_URL.txt -s -a integration

      - name: Create delta packages
        run: |
          mkdir changed-sources
          sfdx sgd:source:delta --to "HEAD" --from "HEAD^" --output changed-sources/ --generate-delta --source force-app/

      - name: Scan code
        run: |
          cd changed-sources
          sfdx scanner:run --format sarif --target './**/*.cls' --category "Design,Best Practices,Performance" --outfile 'apexScanResults.sarif'
          cd ..

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: changed-sources/apexScanResults.sarif

      - name: Deploy delta changes
        run: |
          if [ "${{ env.APEX_TESTS }}" == "all" ]; then
            sfdx force:source:deploy -p "changed-sources/force-app" --checkonly --testlevel RunLocalTests --json;
          else
            sfdx force:source:deploy -p "changed-sources/force-app" --checkonly --testlevel RunSpecifiedTests --runtests ${{ env.APEX_TESTS }} --json;
          fi

      - name: Cleanup temporary files
        run: rm -f pr_body.txt testsToRun.txt SFDX_INTEGRATION_URL.txt
